version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/3-tier-todo-app-frontend-backend

hooks:
  BeforeAllowTraffic:
    - location: scripts/beforeAllowTraffic.sh
      timeout: 300
      runas: ubuntu

  AfterAllowTraffic:
    - location: scripts/afterAllowTraffic.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: ubuntu
